### ISSUE TITLE
Question about stress index.

### ISSUE THREAD

**Issue by DoVan-Thuan** [beamai/BeamAISDK-iOS#3]
Hi @peymanbateni, thank you for your great repo.
I have a small question is how many stress levels that you define and what are thresholds of them?
Thanks in advance.

**Comment by peymanbateni** [comment]
Hi @DoVan-Thuan, thank you for the kind words and we appreciate your interest in our repo.

The stress measurement is based on the Baevsky Stress Index, which is a quantitative measure of stress, where lower values naturally indicate lower stress and conversely higher values indicate greater stress. We provide the details in https://paperswithcode.com/paper/real-time-monitoring-of-user-stress-heart on how we mathematically calculate the Baevsky stress using the user's interbeat-intervals. You can also explore the substantial academic literature that is publicly available on the Baevsky Stress Index. Here is a good reference on the topic: https://www.semanticscholar.org/paper/Heart-rate-variability-analysis%3A-physiological-and-Baevsky-Chernikova/f9aae61bb8301565683a63592ed57e47765b6671.

In general, a resting Baevsky stress reading below 1.5 is considered normal, while numbers higher indicate mild/high levels of stress. Baevsky stress levels at rest above 5.0 indicate very high stress. This can happen when the individual engages in very intensive sports activities or is under considerable pressure in a work / academic environment. However, persistent stress levels above 5.0 can have potential consequences on the wellness of the individual in the long term.

Hope you find the information above useful. Happy to clarify or dive deeper into any aspect of it.

Thank you very much again for your interest in our SDK!

**Comment by DoVan-Thuan** [comment]
Thank you for your useful information. Have a good day 😁
